const SET_AUTH = "SET_AUTH"
const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'
const DEALS_REQUEST = 'DEALS_REQUEST'
const DEALS_SUCCESS = 'DEALS_SUCCESS'
const DEALS_FAILURE = 'DEALS_FAILURE'

export {
    SET_AUTH,
    LOGIN_REQUEST,
    LOGIN_SUCCESS, 
    LOGIN_FAILURE,
    DEALS_REQUEST,
    DEALS_SUCCESS,
    DEALS_FAILURE
}
