const SET_AUTH = "SET_AUTH"
const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGOUT_USER = 'LOGOUT_USER'

export {
    SET_AUTH,
    LOGIN_REQUEST,
    LOGIN_SUCCESS, 
    LOGOUT_USER
}
